---
- name: Deploy nginx
  hosts: webservers
  remote_user: runner
  become: yes
  become_method: sudo

  tasks:
  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Copy index
    ansible.builtin.copy:
      src: ./index.html
      dest: /var/www/html/index.nginx-debian.html
      owner: www-data
      group: www-data
      mode: '0666'
